config/routes.rb
Forms::Application.routes.draw do 
  resources :helps, :path =>'help'
  
  resources :homes
  
  match '/apps/:app_id/forms/:form_id/submissions/csv', to: 'apps/submissions#csv', as: 'csv'
  
  resources :apps do
    scope module: :apps do
      resources :workflows do
        resources :workflow_stages
      end      
      
      match 'submissions_select', to: 'submissions'
      resources :forms do
        resources :submissions do
          resources :workflow_content, :controller =>'workflow_content' do
            get 'approve', :on => :member
            get 'reject', :on => :member
            get 'process_response', :on => :member
          end
        end
        get 'success', :on => :member
        get 'swap_disabled_status', :on => :member
        get 'publish', :on => :member
        get 'new_submission', :on => :member
        match 'save'
      end
    end
  end
  
  get '/roles', to: 'roles#index'
  get '/roles/new', to: 'roles#new'
  
  match '/role/:id/new', to: 'roles#new', as: 'role'
  match '/role/:id', to: 'roles#index_app', as: 'role'
  
  devise_for :users

  root :to => 'homes#index'
  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}
  
  get '*url/' => 'apps#route', format: false
end

app/models/workflow.rb
class Workflow < ActiveRecord::Base
  attr_accessible :created_by_id, :name, :updated_by_id
  has_many :workflow_stages, :dependent => :destroy
  
  belongs_to :created_by, :class_name => "User"
  belongs_to :updated_by, :class_name => "User"     
  
  has_many :workflow_contents, through: :workflow_stages
  
  validates :name, length: { minimum: 2 }, presence: true, uniqueness: true
  belongs_to :app
  has_many :constructs
end

app/controllers/apps/workflows_controller.rb
class Apps::WorkflowsController < ApplicationController

   before_filter :authenticate_user!
   before_filter :find_app 
  
   before_filter lambda { check_permission('view', true) }

  # GET /apps
  # GET /apps.json
  def index  
    @workflows = Workflow.where('app_id = ?', @app.id)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @apps }
    end
  end
  
  def new
    @workflow = (flash[:workflow]) ? flash[:workflow] : Workflow.new
    @new_workflow = true
  
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @workflow }
    end    
  end
  
  def edit

  end  
  
  
  
  def show 
    @workflow = Workflow.find_by_id(params[:id])
  end
    
  def create
    @app = App.find_by_id(params[:app_id])
    @workflow = Workflow.new(params[:workflow])
    @workflow.app_id = @app.id
    @workflow.created_by_id = current_user.id
    @workflow.updated_by_id = current_user.id

    respond_to do |format|
      if @workflow.save
        format.html { redirect_to app_workflow_path(params[:app_id], @workflow), notice: 'Workflow was successfully created.' }
        format.json {  }
      else
        flash[:workflow] = @workflow
        format.html { redirect_to new_app_workflow_path }
        format.json {  }
      end
    end
  end  

end

app/views/apps/workflows/_form.html.erb
<div class="form-horizontal">

	<%= form_for @workflow, :url => (@workflow.id?) ? app_workflow_path(@app, @workflow) : app_workflows_path(@app) do |f| %>

	  <% if @workflow.errors.any? %>
    	<div class="alert alert-danger" id="alert_message">
	      <strong><%= t 'error.count', :count => pluralize(@workflow.errors.count, "error") %></strong>
	
	      <ul>
	      <% @workflow.errors.full_messages.each do |msg| %>
	        <li><%= msg %></li>
	      <% end %>
	      </ul>
	    </div>
	  <% end %>
	
	  <div class="form-group">
	    <%= f.label :name, :class=>'col-sm-2 control-label' %>
	    <div class="col-sm-10">
	    	<%= f.text_field :name, :class=>'form-control', :rows=>5 %>
	    </div>
	  </div>
	  <div class="form-group">
		  <div class="actions col-sm-offset-2 col-sm-10">
		    <%= f.submit "Save", :class=>'btn btn-success' %>
		  </div>
	  </div>
	<% end %>
</div>

app/views/apps/workflows/_workflow.html.erb
<div class="workflow_stage_container">
	<div class="workflow_stage <%= 'completed' if params[:highlight] %>">
		<span class="glyphicon glyphicon-ok"></span>
		Form submitted
	</div>
	
	<%= t('arrows.down_html')%>
</div>

<% workflow.workflow_stages.each do |workflow_stage| %>

	<div class="workflow_stage_container">
		<div class="workflow_stage <%= workflow_stage.info_only? ? 'alert-info' : 'alert-warning' if !params[:highlight] %> <%= 'alert-success' if params[:highlight] and workflow_stage.stage < params[:highlight].to_i %> <%= 'alert-warning' if params[:highlight] and workflow_stage.stage == params[:highlight].to_i %>">
			
			<span class="glyphicon glyphicon-ok"></span>
			
			Send to <strong><%= mail_to workflow_stage.send_to.email, workflow_stage.send_to.name %></strong>
			<%= workflow_stage.info_only? ? t('text.for_info') : t('text.for_approval') %>
			
			<%= link_to t('text.remove_stage_html'), app_workflow_workflow_stage_path(@app, workflow, workflow_stage), { :method => :delete, :remote=>true, :class=>"remove_stage btn btn-danger btn-xs #{ 'hidden_workflow hidden' if workflow.constructs.count > 0}"} if edit and check_role 'admin', @app.id %>
		</div>
		
		<%= t('arrows.down_html')%>
	</div>
<% end %>




<div class="workflow_stage_container" id="final_stage">
	<div class="workflow_stage <%= 'completed' if params[:highlight] and params[:highlight].to_i > workflow.workflow_stages.count %>">
		<span class="glyphicon glyphicon-ok"></span>
		<%= t('text.completed') %>
	</div>
</div>

<% if edit %>
	<div class="workflow_stage_container hidden">
		<div class="workflow_stage">
		</div>
		<%= t('arrows.down_html')%>
	</div>
<% end %>

app/views/apps/workflows/index.html.erb
<h3><strong><%= @app.name %></strong> <%= t('text.workflows').downcase %></h3>
<% if @workflows.count > 0 %>
	
	<div class="panel panel-default">
		<div class="panel-heading">
			<h3 class="panel-title">
				<div class="row">
					<div class="col-sm-3"><%= t('text.name')%></div>
					<div class="col-sm-3"><%= t('text.created')%></div>
					<div class="col-sm-3"><%= t('text.created_by')%></div>
					<div class="col-sm-3"><%= t('text.used')%></div>
				</div>
			</h3>
		</div>
		
		<div class="panel-body no_padding">
			<% @workflows.each do |workflow| %>
				<div class="row">
					<div class="col-sm-3"><%= link_to workflow.name, app_workflow_path(@app, workflow) %></div>
					<div class="col-sm-3"><%= time_tag(workflow.created_at) %></div>
					<div class="col-sm-3"><%= workflow.created_by.name %></div>
					<div class="col-sm-3"><%= workflow.constructs.map(&:name).join(", ") %></div>
				</div>
			<% end %>
		</div>
	</div>
<% else %>
	<%= t('text.no_workflows')%>
<% end %>

<div class="clear"></div>
<%= button_icon_link 'plus', t('text.new_workflow'), new_app_workflow_path, 'success' %>

app/views/apps/workflows/new.html.erb
<h3><%= t('text.new')%> <strong><%= @app.name%></strong> <%= t('text.workflow').downcase %></h3>

<%= render 'form' %>

app/views/apps/workflows/show.html.erb
<h3><strong><%= @workflow.name %></strong> <%= t('text.workflow').downcase %></h3>

<%= render 'workflow', :workflow => @workflow, :edit => true  %>

<% if @workflow.constructs.count > 0  and check_role 'admin', @app.id %>
	<br/></br/>
	<div class="alert alert-warning">
		<%= t('text.workflow_warning_html') %>
		<ul>
		<% @workflow.constructs.each do |construct| %>
			<li><%= link_to construct.name, app_form_path(@app, construct), :class=>'alert-link'  %></li>
		<% end %>
		</ul>
		
		
		<% in_progress_count = 0 %>
		<% @workflow.workflow_contents.each{|workflow_content| in_progress_count = in_progress_count + 1 if workflow_content.status == 'pending' } %>
		
		<% if in_progress_count > 0 %>
			<div class="alert alert-danger"><%= t('text.in_progress_workflows', :count=>pluralize(in_progress_count, 'workflow item'))%></div>
		<% end %>
		
		<%= link_to t('text.ok_i_know'), '#', :class=>'btn btn-default btn-sm', :id=>'enable_workflow_controls' %>
	</div>
<% end %>

<span id="new_stage" class="<%= 'hidden_workflow hidden' if @workflow.constructs.count > 0 %>">
	<%= button_icon_link 'plus', t('text.new_stage'), new_app_workflow_workflow_stage_path(@app, @workflow), "success" %>
</span>