config/routes.rb
Forms::Application.routes.draw do 
  resources :helps, :path =>'help'
  
  resources :homes
  
  match '/apps/:app_id/forms/:form_id/submissions/csv', to: 'apps/submissions#csv', as: 'csv'
  
  resources :apps do
    scope module: :apps do
      resources :workflows do
        resources :workflow_stages
      end      
      
      match 'submissions_select', to: 'submissions'
      resources :forms do
        resources :submissions do
          resources :workflow_content, :controller =>'workflow_content' do
            get 'approve', :on => :member
            get 'reject', :on => :member
            get 'process_response', :on => :member
          end
        end
        get 'success', :on => :member
        get 'swap_disabled_status', :on => :member
        get 'publish', :on => :member
        get 'new_submission', :on => :member
        match 'save'
      end
    end
  end
  
  get '/roles', to: 'roles#index'
  get '/roles/new', to: 'roles#new'
  
  match '/role/:id/new', to: 'roles#new', as: 'role'
  match '/role/:id', to: 'roles#index_app', as: 'role'
  
  devise_for :users

  root :to => 'homes#index'
  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}
  
  get '*url/' => 'apps#route', format: false
end

app/models/workflow_content.rb
class WorkflowContent < ActiveRecord::Base
  attr_accessible :status, :comment

  belongs_to :user
  belongs_to :created_by, :class_name => "User"
  belongs_to :updated_by, :class_name => "User"     
  
  has_many :workflows, through: :workflow_stages
  
  belongs_to :workflow_stage
  belongs_to :submission
end

app/controllers/apps/workflow_content_controller.rb
class Apps::WorkflowContentController < ApplicationController

   before_filter :authenticate_user!
   before_filter :find_app 
   
   before_filter :check_approval_status
   before_filter lambda { check_permission('view', true) }

  def check_approval_status
    @workflow_content = WorkflowContent.find_by_id(params[:id])
    allowed = false
    allowed = true if @workflow_content.status == 'pending' && @workflow_content.workflow_stage.send_to == current_user
    redirect_to app_form_submissions_path(@app, params[:form_id]), :notice=>"#{t('text.not_your_turn')}" unless allowed
    return false
  end

  def approve
    
    @workflow_content = WorkflowContent.find_by_id(params[:id])
    @apps_construct = @workflow_content.submission.construct
    @submission = @workflow_content.submission

  end
  
  def reject
    @workflow_content = WorkflowContent.find_by_id(params[:id])
    @apps_construct = Construct.find_by_id(params[:form_id])
    @submission = @workflow_content.submission
  end
  
  def update
    response = ""
    @workflow_content = WorkflowContent.find_by_id(params[:id])
    @submission = Submission.find_by_id(params[:submission_id])
    
    if @workflow_content.update_attributes(params[:workflow_content])
      response = "#{t('text.submission')} #{ @workflow_content.status }"
      
      create_workflow_stage_content(@submission)
    else
      response = t('text.error_saving_update')
    end
    
    redirect_to app_form_submissions_path(@app, params[:form_id]), :notice=>"#{response}"
  
    
  end

end

app/views/apps/workflow_content/_form.html.erb
<h3><%= params[:action].humanize %> <strong><%= @submission.construct.name %></strong> <%= t('text.submission').downcase %> by <strong><%= @submission.created_by.name %></strong>
	<%= link_to 'View response', app_form_submission_path(@app, @apps_construct, @submission), :class=>'btn btn-default right', :target=>"_blank" %>
</h3>

	<%= form_for @workflow_content, :url => (@workflow_content.id?) ? app_form_submission_workflow_content_path : root_path do |f| %>
	  <% if @app.errors.any? %>
	    <div class="alert alert-danger" id="alert_message">
	      <strong><%= t('error.count', :count => pluralize(@app.errors.count, "error")) %> </strong>
	
	      <ul>
	      <% @app.errors.full_messages.each do |msg| %>
	        <li><%= msg %></li>
	      <% end %>
	      </ul>
	    </div>
	  <% end %>
	  <div class="form-horizontal">	  
		  <div class="form-group">
		  	<%= f.hidden_field :status, :value=>(params[:action] == 'approve') ? 'approved' : 'rejected' %>
		  
		  
		  <label class="col-sm-2 control-label">
		  	<%= '<span class="required">*</span>'.html_safe if params[:action] == 'reject' %>
		  	<%= "Comment #{'(optional)' if params[:action] == 'approve'}" %>
		  </label>
		    <div class="col-sm-10">
		      <% required = false %>
		      <% required = true if params[:action] != 'approve' %>
		      <%= f.text_area :comment, :class=>'form-control no_wysiwyg', :rows=>5, :required=>required  %>
		    </div>
		  </div>  
		  
		
		
		  <div class="actions btn-group">
		    <%= f.submit params[:action].humanize, :class=>"btn btn-#{ (params[:action] == 'approve') ? 'success' : 'danger'}"  %>
   		    <%= button_icon_link('ban-circle', t('text.cancel'), app_form_submissions_path) %>
		  </div>
		<% end %>
	</div>

app/views/apps/workflow_content/approve.html.erb
<%= render 'form' %>

app/views/apps/workflow_content/reject.html.erb
<%= render 'form' %>