config/routes.rb
Forms::Application.routes.draw do 
  resources :helps, :path =>'help'
  
  resources :homes
  
  match '/apps/:app_id/forms/:form_id/submissions/csv', to: 'apps/submissions#csv', as: 'csv'
  
  resources :apps do
    scope module: :apps do
      resources :workflows do
        resources :workflow_stages
      end      
      
      match 'submissions_select', to: 'submissions'
      resources :forms do
        resources :submissions do
          resources :workflow_content, :controller =>'workflow_content' do
            get 'approve', :on => :member
            get 'reject', :on => :member
            get 'process_response', :on => :member
          end
        end
        get 'success', :on => :member
        get 'swap_disabled_status', :on => :member
        get 'publish', :on => :member
        get 'new_submission', :on => :member
        match 'save'
      end
    end
  end
  
  get '/roles', to: 'roles#index'
  get '/roles/new', to: 'roles#new'
  
  match '/role/:id/new', to: 'roles#new', as: 'role'
  match '/role/:id', to: 'roles#index_app', as: 'role'
  
  devise_for :users

  root :to => 'homes#index'
  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}
  
  get '*url/' => 'apps#route', format: false
end

app/models/help.rb
class Help < ActiveRecord::Base
  attr_accessible :content, :created_by_id, :name, :updated_by_id
end

app/controllers/helps_controller.rb
class HelpsController < ApplicationController
  
 # before_filter :authenticate_user!
  
  before_filter lambda { check_permission('top_banana', false) }, :except => [:index]
    
  # GET /helps
  # GET /helps.json
  def index
    @helps = Help.find(:all, :order => "name")
    @release_notes = WorkflowContent.where('comment LIKE "[0.%" OR comment LIKE "[1.%"').order('comment DESC')

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @helps }
    end
  end

  # GET /helps/new
  # GET /helps/new.json
  def new
    @help = Help.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @help }
    end
  end

  # GET /helps/1/edit
  def edit
    @help = Help.find(params[:id])
  end

  # POST /helps
  # POST /helps.json
  def create
    @help = Help.new(params[:help])

    respond_to do |format|
      if @help.save
        format.html { redirect_to helps_path, notice: 'Help was successfully created.' }
        format.json { render json: @help, status: :created, location: @help }
      else
        format.html { render action: "new" }
        format.json { render json: @help.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /helps/1
  # PUT /helps/1.json
  def update
    @help = Help.find(params[:id])

    respond_to do |format|
      if @help.update_attributes(params[:help])
        format.html { redirect_to helps_path, notice: 'Help was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @help.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /helps/1
  # DELETE /helps/1.json
  def destroy
    @help = Help.find(params[:id])
    @help.destroy

    respond_to do |format|
      format.html { redirect_to helps_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/helps_helper.rb
module HelpsHelper
end

app/views/helps/_form.html.erb
<div class="form-horizontal">
<%= form_for(@help) do |f| %>
  <% if @help.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@help.errors.count, "error") %> prohibited this help from being saved:</h2>

      <ul>
      <% @help.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class=>'control-label col-sm-2' %>
    <div class="col-sm-10">
    	<%= f.text_field :name, :class=>'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :content, :class=>'control-label col-sm-2' %>
    <div class="col-sm-10">
    	<%= f.text_area :content, :class=>'form-control' %>
    </div>
  </div>

  <div class="actions btn-group">
    <%= f.submit "Save", :class=>'btn btn-success' %>
    <%= link_to 'Cancel', helps_path, :class=>'btn-default btn' %>
  </div>
<% end %>
</div>

app/views/helps/edit.html.erb
<h1>Editing help</h1>

<%= render 'form' %>

app/views/helps/index.html.erb
<h3>Help</h3>
<div class="help_panel">
	<% @helps.each do |help| %>
		<div class="panel panel-default">
			<div class="panel-heading slide_toggle">
				<h3 class="panel-title"><%= help.name %>
				<% if check_role 'top_banana' %>
					<div class="right btn-group">
						<%= button_closer_link 'ok', 'New', new_help_path, 'success btn-xs' %>
					    <%= button_closer_link 'wrench', 'Edit', edit_help_path(help), 'warning btn-xs' %>
					    <%= button_closer_link 'remove', 'Delete', help, 'danger btn-xs', method: :delete, data: { confirm: 'Are you sure?' } %>
				    </div>
			    <% end %>
					
				</h3>
			</div>
			<div class="panel-body slide_up">
				<%= help.content.html_safe %>
			</div>
		</div>
	<% end %>
</div>


<div class="panel panel-default">
	<div class="panel-heading slide_toggle">
		<h3 class="panel-title"><strong>Release notes</strong></h3>	
	</div>	
	
	<div class="panel-body slide_up">
			<div class="panel panel-default">
				<% current_version = '' %>
				<% @release_notes.each do |release_note| %>
	
				<% release_note.comment = release_note.comment.split(']', 2) %>
				<% if release_note.comment[0] != current_version %>
					<div class="panel-heading">
						<h3 class="panel-title"><%= release_note.comment[0][1..-1] %></h3>
					</div>
				<% current_version = release_note.comment[0] %>
				<% end %>
	
			<div class="panel-body no-vertical-padding">
				<%= release_note.comment[1] %>
			</div>
		<% end %>
		</div>
	</div>
</div>

app/views/helps/new.html.erb
<h3>New help item</h3>

<%= render 'form' %>