config/routes.rb
Forms::Application.routes.draw do 
  resources :helps, :path =>'help'
  
  resources :homes
  
  match '/apps/:app_id/forms/:form_id/submissions/csv', to: 'apps/submissions#csv', as: 'csv'
  
  resources :apps do
    scope module: :apps do
      resources :workflows do
        resources :workflow_stages
      end      
      
      match 'submissions_select', to: 'submissions'
      resources :forms do
        resources :submissions do
          resources :workflow_content, :controller =>'workflow_content' do
            get 'approve', :on => :member
            get 'reject', :on => :member
            get 'process_response', :on => :member
          end
        end
        get 'success', :on => :member
        get 'swap_disabled_status', :on => :member
        get 'publish', :on => :member
        get 'new_submission', :on => :member
        match 'save'
      end
    end
  end
  
  get '/roles', to: 'roles#index'
  get '/roles/new', to: 'roles#new'
  
  match '/role/:id/new', to: 'roles#new', as: 'role'
  match '/role/:id', to: 'roles#index_app', as: 'role'
  
  devise_for :users

  root :to => 'homes#index'
  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}
  
  get '*url/' => 'apps#route', format: false
end

app/views/apps/_form.html.erb
	<%= form_for(@app) do |f| %>
	  <% if @app.errors.any? %>
	    <div class="alert alert-danger" id="alert_message">
	      <strong><%= t('error.count', :count => pluralize(@app.errors.count, "error")) %> </strong>
	
	      <ul>
	      <% @app.errors.full_messages.each do |msg| %>
	        <li><%= msg %></li>
	      <% end %>
	      </ul>
	    </div>
	  <% end %>
	  <div class="form-horizontal">	  
		  <div class="form-group">
		    <%= f.label :name, :class=>'col-sm-2 control-label' %>
		    <div class="col-sm-10">
		    	<%= f.text_field :name, :class=>'form-control', :rows=>5 %>
		    </div>
		  </div>  
		  
		
		  <div class="form-group">
		    <%= f.label :app_type, :class=>'col-sm-2 control-label' %>
		    <div class="col-sm-10">
		    	<%= f.select(:app_type, options_for_select(app_types, @app.app_type), {}, { :disabled => @app.app_type == 99 ? true : false, :class=>'form-control'}) %>
		    </div>
		  </div>    
		  
		  <div class="form-group">
		    <%= f.label :description, :class=>'col-sm-2 control-label' %>
		    <div class="col-sm-10">
		    	<%= f.text_area :description, :class=>'form-control', :rows=>5 %>
		    </div>
		  </div>
		
		  <div class="actions btn-group">
		    <%= f.submit t('text.save'), :class=>'btn btn-success'  %>
   		    <%= button_icon_link('ban-circle', t('text.cancel'), @app.id ? app_path(@app.id) : apps_path) %>
		  </div>
		<% end %>
	</div>

app/views/apps/edit.html.erb
<%= render 'form' %>

app/views/apps/index.html.erb
<% 
	no_apps = true
	@apps.each do |app|
		if check_role 'view', app.id
			no_apps = false %>
		<%= link_to app.name, app_path(app), :class=>'btn btn-block btn-default' %>
	<% end%>
<% end %>

<% if no_apps %>
	<div class="alert alert-warning">There are currently no applications available.</div>
<% end %>
<br/>
<%= link_to '<span class="glyphicon glyphicon-plus"></span> <span class="toggle_text">Create an app</span>'.html_safe, new_app_path, :class=>'btn btn-success margin-bottom' if check_role 'create' %>

app/views/apps/route.html.erb
<div class="alert alert-danger">Couldn't find the page you were looking for.</div>

<%= link_to 'Return to home page', root_path, :class=>'btn btn-block btn-default' %>

app/views/apps/show.html.erb
<% @home.each do |home| %>
	<%= home.content.html_safe %>
	<%= button_closer_link 'pencil', t('text.edit_page_content'), edit_home_path(home), 'warning btn-xs right' if check_role 'edit', @app.id %>
<% end %>






<% if check_role 'edit', @app.id %>
<br/><br/>

	<div class="panel panel-default">
		<div class="panel-heading"><h3 class="panel-title">Admin</h3></div>
		<div class="panel-body">
			<div class="alert alert-success"><strong><%= app_types.select{ |x| x[1] == @app.app_type }.first.first %></strong> application</div>
			<%= "<div class='alert alert-info'>#{@app.description}</div>".html_safe if @app.description? %>
			
			<div class="alert alert-warning">
				<input type="text" id="distribute_url" value="<%= "#{root_url}#{@app.name.parameterize}" %>">
			</div>
			
			<%= render :partial => '/partials/created_updated_details', :locals => { :item => @app } %>
			
			<div class="btn-group">
				<%= button_closer_link 'pencil', t('text.edit'), edit_app_path(@app), 'warning' if check_role 'edit', @app.id %>
				<%= button_closer_link 'remove', t('text.delete'), {:action => 'destroy', :id => @app.id }, 'danger', { :method => :delete, :confirm => "#{ t('confirm.delete_app', :app_name => @app.name)}" } if check_role 'delete', @app.id %>	
			</div>
			
			<% if check_role 'view', @app.id %>
				<div class="btn-group">
					<%= button_icon_link 'wrench', t('text.forms'), app_forms_path(@app) %>	
					<%= button_icon_link 'stats', t('text.responses'), app_submissions_select_path(@app)%>
					<%= button_icon_link 'thumbs-up', t('text.permissions'), role_path(@app) if check_role 'admin', @app.id %>
					<%= button_icon_link 'tasks', t('text.workflows'), app_workflows_path(@app) if @app.app_type == 2 %>
				</div>
			<% end %>
		</div>
	</div>
<% end %>